apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
  labels:
    app: my-appp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-appp
  template:
    metadata:
      labels:
        app: my-appp
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
        ports:
        - containerPort: 80
